=== 2000abhi/ncp-xml/XML1/survey.dtd
<!ELEMENT survey(isro +)>
<!ELEMENT isro(Region,Location,FeatureType,ROVDives,AreaCovered,Depth,LandDistance,Proxy,Items)>
<!ELEMENT Region(#PCDATA)> 
<!ELEMENT Location(#PCDATA)>
<!ELEMENT FeatureType(#PCDATA)>
<!ELEMENT ROVDives(#PCDATA)>
<!ELEMENT AreaCovered(#PCDATA)>
<!ELEMENT Depth(#PCDATA)>
<!ELEMENT LandDistance(#PCDATA)>
<!ELEMENT Proxy(#PCDATA)>
<!ELEMENT Items(#PCDATA)>

=== 2000abhi/ncp-xml/survey.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="sheetstyle.xsl"?>
<?xml-stylesheet type="text/css" href="styles.css"?>

<!DOCTYPE survey SYSTEM "survey.dtd">
<survey>
<isro>
<Region>Atlantic</Region>
<Location>Carter</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>5</ROVDives>
<AreaCovered>2.78</AreaCovered>
<Depth>200-2800</Depth>
<LandDistance>630</LandDistance>
<Proxy>0.12</Proxy>
<Items>12.23</Items>
</isro>

<isro>
<Region>Atlantic</Region>
<Location>Knipovich</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>3</ROVDives>
<AreaCovered>2.18</AreaCovered>
<Depth>600-2800</Depth>
<LandDistance>1360</LandDistance>
<Proxy>0.23</Proxy>
<Items>2.29</Items>
</isro>

<isro>
<Region>Atlantic</Region>
<Location>VEMA</Location>
<FeatureType>Fracture zone</FeatureType>
<ROVDives>3</ROVDives>
<AreaCovered>1.80</AreaCovered>
<Depth>600-3000</Depth>
<LandDistance>1040</LandDistance>
<Proxy>0.07</Proxy>
<Items>5.56</Items>
</isro>

<isro>
<Region>Atlantic</Region>
<Location>Vayda</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>3</ROVDives>
<AreaCovered>3.10</AreaCovered>
<Depth>400-2300</Depth>
<LandDistance>1170</LandDistance>
<Proxy>0.01</Proxy>
<Items>1.94</Items>
</isro>

<isro>
<Region>Atlantic</Region>
<Location>Gramberg</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>2</ROVDives>
<AreaCovered>1.70</AreaCovered>
<Depth>900-2200</Depth>
<LandDistance>940</LandDistance>
<Proxy>0.21</Proxy>
<Items>0.59</Items>
</isro>

<isro>
<Region>Indian</Region>
<Location>Coral</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>5</ROVDives>
<AreaCovered>2.04</AreaCovered>
<Depth>500-1500</Depth>
<LandDistance>1610</LandDistance>
<Proxy>0.01</Proxy>
<Items>1.47</Items>
</isro>

<isro>
<Region>Indian</Region>
<Location>Melville</Location>
<FeatureType>Bank</FeatureType>
<ROVDives>4</ROVDives>
<AreaCovered>1.35</AreaCovered>
<Depth>100-1300</Depth>
<LandDistance>1440</LandDistance>
<Proxy>0.00</Proxy>
<Items>13.33</Items>
</isro>

<isro>
<Region>Indian</Region>
<Location>Middle of What</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>3</ROVDives>
<AreaCovered>0.41</AreaCovered>
<Depth>1000-1400</Depth>
<LandDistance>1460</LandDistance>
<Proxy>0.00</Proxy>
<Items>2.44</Items>
</isro>

<isro>
<Region>Indian</Region>
<Location>Sapmer</Location>
<FeatureType>Seamount</FeatureType>
<ROVDives>1</ROVDives>
<AreaCovered>0.46</AreaCovered>
<Depth>300-700</Depth>
<LandDistance>1390</LandDistance>
<Proxy>0.00</Proxy>
<Items>17.39</Items>
</isro>

<isro>
<Region>Indian</Region>
<Location>Atlantis</Location>
<FeatureType>Bank</FeatureType>
<ROVDives>3</ROVDives>
<AreaCovered>1.34</AreaCovered>
<Depth>700-1200</Depth>
<LandDistance>1320</LandDistance>
<Proxy>0.10</Proxy>
<Items>0.75</Items>
</isro>
</survey>
